"""agregar tablas garantia y devolucion

Revision ID: 15427642f883
Revises: 5cc1197b8c7f
Create Date: 2026-09-15 14:52:10.205038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15427642f883'
down_revision = '5cc1197b8c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucion',
    sa.Column('id_devolucion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_devolucion')
    )
    op.create_table('garantia',
    sa.Column('id_garantia', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_garantia')
    )
    op.drop_table('proveedor_producto')
    op.drop_table('detalle_movimiento')
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('id_producto',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.alter_column('tipo_movimiento',
               existing_type=mysql.ENUM('ENTRADA', 'SALIDA', 'AJUSTE'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('stock_actual',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stock_minimo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('id_categoria',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('id_marca')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('tipo_documento',
               existing_type=mysql.ENUM('CC', 'CE', 'NIT', 'PP'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('documento',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('id_rol',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_rol',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('documento',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('CC', 'CE', 'NIT', 'PP'),
               existing_nullable=False)

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_marca', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('id_categoria',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('stock_minimo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('stock_actual',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('tipo_movimiento',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('ENTRADA', 'SALIDA', 'AJUSTE'),
               existing_nullable=False)

    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('mensaje',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)

    op.create_table('detalle_movimiento',
    sa.Column('id_detalle', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_movimiento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimiento.id_movimiento'], name=op.f('detalle_movimiento_ibfk_1')),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], name=op.f('detalle_movimiento_ibfk_2')),
    sa.PrimaryKeyConstraint('id_detalle'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor_producto',
    sa.Column('id_proveedor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], name=op.f('proveedor_producto_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], name=op.f('proveedor_producto_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_proveedor', 'id_producto'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('garantia')
    op.drop_table('devolucion')
    # ### end Alembic commands ###
