"""Agregar columna correo a tabla usuario

Revision ID: 5cc1197b8c7f
Revises: 56e739f3a7c4
Create Date: 2026-06-22 17:33:01.662140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc1197b8c7f'
down_revision = '56e739f3a7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('correo')

    # ### end Alembic commands ###
